// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface IPlaidTransaction {
    account_id: string;
    account_owner: null;
    amount: number;
    authorized_date: null;
    category: string[];
    category_id: string;
    date: string;
    iso_currency_code: string;
    location: Location;
    name: string;
    payment_channel: string;
    payment_meta: PaymentMeta;
    pending: boolean;
    pending_transaction_id: null;
    transaction_code: null;
    transaction_id: string;
    transaction_type: string;
    unofficial_currency_code: null;
}

export interface Location {
    address: null;
    city: null;
    country: null;
    lat: null;
    lon: null;
    postal_code: null;
    region: null;
    store_number: null;
}

export interface PaymentMeta {
    by_order_of: null;
    payee: null;
    payer: null;
    payment_method: null;
    payment_processor: null;
    ppd_id: null;
    reason: null;
    reference_number: null;
}
