// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface LoginResponse {
    Ca:          string;
    uc:          TokenObj;
    Qt:          Qt;
    googleId:    string;
    tokenObj:    TokenObj;
    tokenId:     string;
    accessToken: string;
    profileObj:  ProfileObj;
}

export interface Qt {
    SU: string;
    Ad: string;
    vW: string;
    wU: string;
    UK: string;
    zu: string;
}

export interface ProfileObj {
    googleId:   string;
    imageUrl:   string;
    email:      string;
    name:       string;
    givenName:  string;
    familyName: string;
}

export interface TokenObj {
    token_type:      string;
    access_token:    string;
    scope:           string;
    login_hint:      string;
    expires_in:      number;
    id_token:        string;
    session_state:   SessionState;
    first_issued_at: number;
    expires_at:      number;
    idpId:           string;
}

export interface SessionState {
    extraQueryParams: ExtraQueryParams;
}

export interface ExtraQueryParams {
    authuser: string;
}
